SKKU-OSP/SKKU-OSP

osp/home/templates/home/statistic.html
osp/static/css/style.css

home/templates/home/statistic.html
static/css/style.css

home templete refactoring

---

osp/message/templates/message/list-view.html
osp/message/urls.py
osp/message/views.py
osp/static/js/base.js
osp/templates/community/article-bar.html
osp/templates/community/article/includes/content-view.html

새로운 사람에게 메세지 보내기

---

osp/community/templates/community/board/board.html
osp/static/css/base.css
osp/static/css/color.css
osp/team/templates/team/apply-list.html

design: 팀원 모집 수락/거절/삭제/대기 버튼 css 수정

---

osp/community/templates/community/account-card.html
osp/community/templates/community/board/user-board.html
osp/static/css/community-base.css

refactor: user card 코드 리팩토링

---

osp/community/views.py

fix: 팀 초대/신청 승인 중복 오류 수정

---

osp/common/templates/common/register.html
osp/common/views.py
osp/static/css/base.css
osp/tag/templatetags/tag_templatetag.py

- 이메일 정규식 체크 추가
- 이메일 리스트 업데이트
- id 속성 언더스코어 하이픈으로 교체

fix: 회원가입에서 이메일이 올바르게 설정되지 않는 오류 수정

---

osp/community/templates/community/activity.html
osp/community/templates/community/article/article.html
osp/community/templates/community/board/user-board.html
osp/community/templates/community/main.html
osp/community/templates/community/sidebar.html
osp/home/templates/home/statistic.html
osp/message/templatetags/message_tag.py
osp/static/css/base.css
osp/static/css/community-base.css
osp/static/js/community_sidebar.js
osp/static/js/team_application.js
osp/team/templates/team/apply-list.html
osp/templates/header.html

- 헤더 정렬
- admin link 이동
- 반응형 웹 디자인 강화
- 팀 지원서 알림 추가

Feature/design - 헤더 및 사이드바 디자인 개선

---

osp/common/templates/common/login.html
osp/community/templates/community/article-table.html
osp/community/templates/community/comment-table.html
osp/community/templates/community/sidebar.html
osp/community/templates/community/tableBoard/searched.html
osp/community/views.py
osp/home/views.py
osp/message/templatetags/message_tag.py
osp/message/urls.py
osp/message/views.py
osp/osp/settings.py
osp/static/css/base.css
osp/static/css/community-base.css
osp/static/js/base.js
osp/static/js/team_application.js
osp/team/templates/team/apply-list.html
osp/team/templatetags/team_tag.py
osp/templates/header.html

- django 4.1 문서에 따라 로그아웃을 post 요청으로 교체
- 팀 모집 게시판에서 모집 정보 표시 오류를 수정하고 검색, 게시판 내 활동 목록의 팀 모집 글 양식 통일
- 팀 지원서에서 보낸 지원서와 받은 지원서 읽을 때 지원 관련 알림을 읽음 처리하도록 개선

Feature/manage - 로그아웃, 리다이렉션, 게시판, 지원서 동작 개선

---

osp/community/templates/community/activity.html
osp/community/templates/community/article-bar.html
osp/community/templates/community/article-table.html
osp/community/templates/community/article/article.html
osp/community/templates/community/article/includes/comments.html
osp/community/templates/community/article/includes/content-edit.html
osp/community/templates/community/article/includes/content-view.html
osp/community/templates/community/board/board.html
osp/community/templates/community/board/user-board.html
osp/community/templates/community/main.html
osp/community/templates/community/tableBoard/searched.html
osp/community/templates/community/tableBoard/table-board.html
osp/community/urls.py
osp/community/views.py
osp/community/views_api.py
osp/community/views_legacy.py
osp/static/css/color.css
osp/static/css/community-base.css
osp/static/js/article.js
osp/templates/header.html

- 게시글 쓰기/수정/삭제 코드 리팩토링
- 팀장 공지 쓰기 기능
- admin 공지 쓰기 기능 (전체공지)
- 접근권한 설정
- 게시글 디자인 개선

Feature/notice - 공지 기능 추가

---

osp/community/views.py
osp/community/views_api.py
osp/static/js/community_sidebar.js
osp/user/views.py

- 본인 추천
- 본인 조회 체크
- 프로필 리포지토리 대상 확대

Feature/community/action - 유저 행동에 대한 피드백 보완

---

osp/community/templates/community/account-card.html
osp/community/templates/community/activity.html
osp/community/templates/community/article-table.html
osp/community/templates/community/article/includes/content-edit.html
osp/community/templates/community/article/includes/content-view.html
osp/community/templates/community/board/activity-searcher.html
osp/community/templates/community/board/user-board.html
osp/community/templates/community/board/user-searcher.html
osp/community/templates/community/tableBoard/searched.html
osp/community/templates/community/tableBoard/table-board.html
osp/community/urls.py
osp/community/views.py
osp/static/css/base.css
osp/static/css/community-base.css
osp/static/js/searcher.js

- 필터 메커니즘 개선
- 페이지네이션 메커니즘 개선
- 디자인 개선

Feature/user recommend - 맞춤 유저 추천 시스템 개선

---

osp/common/templates/registration/email_reset_password.html
osp/common/templates/registration/subject_reset_password.txt
osp/common/views.py
osp/osp/settings.py

- 설정에 변수 탐지 조건문 추가
- 중복 발송 문제 수정
- 한국어 이메일 템플릿 오버라이딩

Feature/email - 계정찾기 관련 이메일 안정화

---

osp/rank/templates/rank/user_rank.html
osp/static/css/community-base.css
osp/static/css/rank.css

fix: rank 페이지의 페이지네이션 디자인 오류 수정

---

osp/community/templates/community/article/article.html
osp/community/templates/community/article/includes/comments.html
osp/community/templates/community/article/includes/content-view.html
osp/community/templates/community/tableBoard/table-board.html
osp/community/views_api.py
osp/static/css/community-base.css
osp/static/js/article.js
osp/static/js/comment.js
osp/static/js/community_sidebar.js
osp/team/views.py

- 팀 생성/수정 중복 요청 문제 해결
- 게시글 생성/수정/삭제 중복 요청 문제 해결
- 댓글 생성 중복 요청 문제 해결
- 댓글 기능 리팩토링

Feature/ajax - 중복 요청 문제 해결

---

osp/community/templates/community/article-bar.html
osp/community/templates/community/article-table.html
osp/community/templates/community/article/includes/content-view.html
osp/community/templates/community/main.html

- 닉네임을 볼 수 있도록 변경
- 드롭다운 메뉴는 볼 수 없도록 유지

refactor: 비로그인 유저의 게시글 글쓴이 보기 권한 변경

---

osp/community/templates/community/board/team-tab.html
osp/community/views.py
osp/static/js/community_sidebar.js
osp/team/templates/team/update-form.html
osp/team/views.py
osp/user/views_edit.py

- 서버에서 피드백 메시지 전송
- 팀 생성과 팀 수정의 피드백 구조 동일하게 통일
- 팀 수정 시 팀 게시판의 이름이 변경되지 않던 오류 수정

Feature/team - 팀 생성/수정 및 피드백 수정

---

osp/static/css/guideline.css
osp/static/js/profile_visualization.js
osp/user/templates/profile/profile.html
osp/user/templates/profile/repo.html
osp/user/views.py

- 작동하지 않는 버튼 비활성화
- 리포지토리 페이지 반응형 웹 적용
- 프로필 페이지 접근 메커니즘 변경

Feature/profile - 프로필 페이지 UX 개선

---

osp/community/views.py
osp/templates/header.html

feat: 검색창을 커뮤니티에서만 렌더링하도록 개선

---

osp/community/templates/community/article/article.html
osp/static/js/article.js

- html을 검사하지 않고 text 검사
- articl.init 함수를 두번 호출하여 불필요한 오류가 일어나던 현상 수정

fix: 게시글 내용 공백 체크 기능 보완

---

osp/static/js/profile_edit.js
osp/user/templates/profile/profile-edit.html
osp/user/templates/profile/profile.html

Commits on Mar 31, 2023
[feature(profile): 저장시에 알림이 뜨도록 하였습니다.]
[fix(profile): 사용언어 기술스택이 없을시에 숙련도 단계가 보이지 않도록 하였습니다.

Profile edit/alertnimage

---

osp/static/css/base.css
osp/static/css/profile-style.css
osp/static/js/profile_modal.js
osp/static/js/profile_visualization.js
osp/user/templates/profile/profile.html

- 기여내역 시각화의 분포 함수 리뉴얼
- JS 코드 리팩토링
- 프로필 카드에 반응형 적용
- 리포지토리의 텍스트가 튀어나오는 현상 개선

Feature/profile - 기여내역 시각화 개선

---

osp/community/templates/community/article/includes/content-view.html
osp/static/js/article.js

- article 객체가 활성화되지 않아 게시글 작성이 불가능한 문제 해결

fix: 게시글 작성 오류 수정

---

osp/common/views.py

fix: 크롤러 실행 중일 때, github check기능이 동작하지 않는 현상 수정

---

osp/static/css/profile-style.css
osp/static/js/profile_basic.js
osp/static/js/profile_modal.js
osp/static/js/profile_visualization.js
osp/user/templates/profile/chart-modal.html
osp/user/templates/profile/profile.html
osp/user/urls.py
osp/user/views.py

- chart modal 을 다른 html로 분리
- chat data를 api를 통해 ajax로 받아오도록 분리

Feat/profile - 프로필 페이지 chart 관련 데이터 분리

---

osp/common/templates/common/login.html
osp/common/templates/common/register.html
osp/common/urls.py
osp/common/views.py
osp/osp/settings.py
osp/static/css/base.css

- GitHub OAuth 세팅 추가
- GitHub OAuth 관련 로그인/회원가입 페이지 개선
- GitHub OAuth 이용한 기본 데이터 수집 구현

Feature/GitHub oauth - GitHub OAuth 로그인 구현

---

osp/common/views.py
osp/crawler/Scrapy/SKKU_GitHub/middlewares.py
osp/crawler/Scrapy/SKKU_GitHub/pipelines.py
osp/crawler/Scrapy/SKKU_GitHub/settings.py
osp/crawler/Scrapy/SKKU_GitHub/spiders/github.py
osp/crawler/Scrapy/SKKU_GitHub/spiders/github_recent.py
osp/home/updateChart.py
osp/osp/settings.py
osp/user/views.py

- 기존 configure 파일이나 dev_setting에 의존적이던 모듈을 setting의존으로 변경
- 환경변수별 다른 세팅값을 로드할 수 있도록 변경

feat: secret 변수 통합

---

osp/community/templates/community/board/team-tab.html
osp/static/js/community_sidebar.js
osp/static/js/searcher.js

- 검색창에 빈칸을 입력했을 때도 검색이 되는 오류 수정
- Form 피드백 jquery 오류 수정

Fix/community 커뮤니티 검색 기능 및 Form 피드백 기능 오류 수정

---

osp/community/templates/community/article/article.html
osp/community/templates/community/article/includes/content-edit.html

fix: 게시글 수정할 때 정보공개 문구 출력되는 오류 수정

---

osp/community/templates/community/article/includes/comments.html
osp/static/js/comment.js

- 빈칸 체크
- 삭제 후 댓글 등록 불가 현상 수정
- 등록/삭제 알림 성공 메시지 삭제

fix: 댓글 입력 관련 오류 수정

---

osp/community/templates/community/article/article.html
osp/community/views.py

- 팀 게시글 열람 오류 수정
1. 로그인하지 않았을 때
2. 팀원이 아닐 때

fix: team-article

---

osp/community/templates/community/board/searcher.html
osp/community/templates/community/sidebar.html
osp/message/urls.py
osp/message/views.py
osp/static/css/base.css
osp/static/js/base.js
osp/templates/head.html
osp/templates/header.html

- 헤더, 사이드바, 검색창 툴팁 추가
- 알림 모두 읽음 기능 추가

Feature/tooltip - 툴팁 추가

---

osp/static/js/article.js

팀 모집 게시글 작성 시, 모집 기간이 최소 1시간이 되어야 글을 등록할 수 있도록 수정

team-recruit

---

frontend/src/components/Community/Community.css
frontend/src/components/Community/SideBar/SideBar_Presenter.jsx
frontend/src/components/Login.jsx
frontend/src/components/MainHeader.jsx
frontend/src/components/MainHeader.module.css
frontend/src/components/NavBar/Chat/ChatMessageModal_Container.jsx
frontend/src/components/OAuth.jsx
frontend/src/main.jsx
frontend/src/routes/RootLayout.jsx
frontend/src/utils/auth-context.jsx
frontend/src/utils/auth.jsx
osp/community/serializers.py
osp/user/urls.py
osp/user/views.py

- useContext를 활용한 로그인 유저 관리 추가
- local storage를 활용한 토큰 저장 기능 추가
- 프론트엔드 헤더 및 사이드바 개선

Feature/auth - 프론트엔드 사용자 인증 추가 

---

frontend/src/components/Login.jsx
osp/common/urls.py
osp/common/views.py

feat: username과 password 입력한 로그인 기능 추가

---

frontend/src/components/Community/Article/Article_Presenter.jsx
frontend/src/components/Community/Article/TinyArticle/Comment.jsx
frontend/src/components/Community/Article/TinyArticle/Comment_Item.jsx
frontend/src/components/Community/Article/TinyArticle/Content_View.jsx
frontend/src/components/User/TinyUser/Frame/Activity.jsx
frontend/src/components/User/TinyUser/Frame/Interest.jsx
frontend/src/components/User/TinyUser/Frame/Modal/Interest_modal.jsx
frontend/src/components/User/TinyUser/Frame/Owner_Info.jsx
frontend/src/components/User/TinyUser/Profile_Activity.jsx
frontend/src/components/User/TinyUser/Profile_Info.jsx
frontend/src/components/User/TinyUser/Profile_Tab.jsx
frontend/src/components/User/User.css
frontend/src/components/User/User_Container.jsx
frontend/src/components/User/User_Presenter.jsx
frontend/src/components/User/index.jsx
frontend/src/main.jsx
frontend/src/routes/UserPage.jsx

Feat. 프로필 페이지 추가

---

osp/community/urls.py
osp/community/views_article.py

- 기존 html로 렌더링하는 코드를 API View로 변환

feat: 댓글 조회/삭제/ 좋아요 기능 추가

---

osp/osp/settings.py
osp/tag/views.py
osp/user/urls.py
osp/user/views_profile.py

- tag의 type 조건 검색시 콤마로 OR 검색할 수 있는 기능 추가

feat: 유저 관심분야 및 사용언어 업데이트 기능 추가

---

osp/community/serializers.py
osp/community/urls.py
osp/community/views.py
osp/community/views_article.py

feat: 게시글 좋아요 및 스크랩 수 조회 추가

---

frontend/src/components/User/TinyUser/Frame/Interest.jsx
frontend/src/components/User/TinyUser/Frame/InterestModal.jsx
frontend/src/components/User/TinyUser/Frame/SkillModal.jsx
frontend/src/components/User/TinyUser/ProfileInfo.jsx
frontend/src/components/User/User.css
frontend/src/main.jsx
osp/user/views_profile.py

feat. 프로필 페이지 태그 이미지 구현 완료

---

frontend/src/components/Statistics/AnnualDetails.jsx
frontend/src/components/Statistics/AnnualSelectors.jsx
frontend/src/components/Statistics/Charts/Histogram.jsx
frontend/src/components/Statistics/DetailCardContent.jsx
frontend/src/components/Statistics/FactorDists.jsx
frontend/src/components/Statistics/FactorSelectors.jsx
frontend/src/components/Statistics/Statistic.css
frontend/src/components/Statistics/StatisticMain.jsx
frontend/src/components/Statistics/Statistic_Container.jsx

- 컴포넌트 분리
- factor, 개별-합계 스위치, 연도 선택 등 상호작용 추가
- factor 분포 히스토그램 추가

Feature/statistic - statistic 페이지 데이터 상호작용 

---

frontend/src/components/Community/Article/Article_Presenter.jsx
frontend/src/components/Community/Article/TinyArticle/Comment.jsx
frontend/src/components/Community/Article/TinyArticle/CommentItem.jsx
frontend/src/components/Community/Article/TinyArticle/ContentView.jsx

- 작성자 드롭다운
- 게시글의 댓글 보임
- 추천, 스크랩 버튼 클릭 시 로그인 알림 창 띄우기
- 팀 모집 게시글에서 지원하기 버튼 회색으로 ui 변경
- 로그인 후 자신의 게시글 스크랩 불가능 알림 창 추가

fix: 비로그인 상태에서 테스트 시 오류 나는 부분 수정

---

frontend/src/components/Community/Article/ArticleRegister/ArticleRegister.jsx

- 팀 미 선택 시 알림 없는 오류 개선
- 본문 미 작성 시 알림 없는 오류 개선
- 모집 기간 형식 변환 수정
- 팀 선택하고 나면 팀 선택 창 닫히도록 변경

feat: 게시글 등록 시 알림 관련 오류 수정

---

frontend/src/components/Community/Article/ArticleEdit/ArticleEdit.jsx

- 기존의 팀 이름이 보이도록 수정
- 본문 미 작성 시 알림 창
- 날짜 모집 기간 형식 변환
- 수정하기 -> 저장하기로 명칭 변경

feat: 팀 모집 게시글 수정 시 오류 수정

---

frontend/src/components/Community/Article/ArticleRegister/ArticleRegister.jsx

- 본문 미 작성 시 알림 창
- url에 / 빠진 부분 추가

feat: 게시글 수정 시 오류 수정

---

frontend/src/components/Community/Team/TeamBoard/MyTeamList.jsx
frontend/src/components/Community/Team/TeamRecruit/TeamRecruit.jsx

- 드롭다운 item 클릭 시에 계속 열려 있는 현상 수정

feat: 팀 모집 페이지 정렬 기능 추가

---

frontend/src/components/Community/Article/ArticleEdit/ArticleEdit.jsx

getAuthConfig()와 getArticle의 '/' 추가

fix(article): 게시글 수정 에러 수정

---

frontend/src/components/Account/Login.jsx
osp/osp/middleware.py
osp/osp/settings.py

로그인 시, 토큰이 남아있어서 충돌하는 문제를 해결하였습니다.

fix(Login): 로그인 시, 토큰 관리 오류 해결

---

frontend/src/components/Account/Login.jsx

토큰이 있을 경우 setUser() 추가하여 로그인 기록을 유지합니다.

fix(Login): 토큰이 있을 경우 setUser() 추가

---

frontend/src/components/Community/Board/Board.css
frontend/src/components/Community/Board/Board_Presenter.jsx
frontend/src/components/Community/Board/MainBoard/MainBoard_Container.jsx
frontend/src/components/Community/Board/MainBoard/MainBoard_Presenter.jsx
frontend/src/components/Community/Board/MiniBoardArticle/MiniBoardArticle_Container.jsx
frontend/src/components/Community/Board/MiniBoardArticle/MiniBoardArticle_Presenter.jsx
frontend/src/components/Community/Board/MiniBoardArticle/index.jsx
frontend/src/components/Community/Board/MiniBoardTeamList/MiniBoardTeamList_Container.jsx
frontend/src/components/Community/Board/MiniBoardTeamList/MiniBoardTeamList_Presenter.jsx
frontend/src/components/Community/Board/MiniBoardTeamList/index.jsx
frontend/src/components/Community/Board/MiniBoardTeamRecruit/MiniBoardTeamRecruit_Container.jsx
frontend/src/components/Community/Board/MiniBoardTeamRecruit/MiniBoardTeamRecruit_Presenter.jsx
frontend/src/components/Community/Board/MiniBoardTeamRecruit/index.jsx
frontend/src/components/Community/Community.css
frontend/src/components/Community/Team/TeamRecruit/TeamRecruit.jsx
frontend/src/main.jsx
frontend/src/routes/HomePage.jsx

- Hero 영역 구현
- 아래 미니 게시판(커뮤니티 및 팀 모집) 구현

feature: Hero 영역 포함된 메인 게시판 개설

---

frontend/src/components/User/DashBoard/DashBoard.jsx
frontend/src/components/User/TinyUser/Frame/Activity.jsx
frontend/src/components/User/User.css

feat(DashBoard): 신규 유저 크롤링 데이터 없을 때 화면 표시

---

frontend/src/components/User/TinyUser/Frame/QnAModal.jsx
frontend/src/components/User/TinyUser/ProfileInfo.jsx
frontend/src/components/User/User.css

- 문의하기 모달 창 추가
- 질문 유형 선택 가능
- 내용 제출 시 운영자 계정 메시지로 전달

feat: 문의하기 기능 개설

---

frontend/src/components/Community/Article/ArticleRegister/ArticleRegister.jsx
frontend/src/components/Community/Team/TeamRecruit/RecruitArticle.jsx
osp/community/views.py

- 팀 모집 글 작성 시 기간 업데이트 불가 오류 해결
- 모집 전 게시글이 모집중으로 띄워지는 오류 해결

fix: 팀 모집 기간 관련 오류 해결

---

frontend/src/components/SignUp/SignUpForm.jsx
osp/common/views.py

1. 깃허브 유저네임 체크 삭제
이미 github 로그인을 통해 넘어오기 때문에 불필요한 check버튼 삭제
2. 소속 대학을 formData에 업데이트 하는 로직 추가
formData에 소속 대학 필드를 업데이트 하는 로직이 누락되어 있어서 수정 완료

회원가입 페이지 전반적인 버그 수정

---

osp/user/views.py

profile-info api 보안 취약점 해결

---

frontend/src/components/User/TinyUser/ProfileInfo.jsx

프로필 소개 페이지에서 글자수 오버플로우가 발생하지 않도록 글자수 제한을 추가하였습니다

프로필 수정 글자수 제한 & 줄바꿈 제한 추가

---

frontend/src/components/Statistics/AnnualOverviews.jsx
frontend/src/components/Statistics/Charts/DetailChart.jsx
frontend/src/components/Statistics/Charts/DistChart.jsx
frontend/src/components/Statistics/Charts/Histogram.jsx
frontend/src/components/Statistics/Charts/OverviewChart.jsx
frontend/src/components/Statistics/StatisticMain.jsx
frontend/src/components/Statistics/Statistic_Container.jsx

1. 통계 화면 로딩 컴포넌트 추가
2. 통계 화면 새로고침 시 destroy 관련 충돌로 인해 발생하는 버그 해결

통계 로딩 화면 추가 및 chart destroy 버그 해결

---

frontend/src/components/NavBar/MainHeader.css
frontend/src/index.css

모바일페이지 로그인버튼 수정

---

frontend/src/routes/ChallengePage.jsx

관리자 챌린지 게시판 추가

---

frontend/src/components/Community/Article/Article.css
frontend/src/components/Community/Article/ArticleEdit/ArticleEdit.css
frontend/src/components/Community/Article/TinyArticle/ContentView.jsx
frontend/src/components/User/TypeTest/DevType.jsx
frontend/src/components/User/User.css

유저 프로필 모바일 UI 개선
커뮤니티 게시글 UI 개선
- PC, 모바일에서의 가독성 향상
- closes #이슈번호

유저 프로필 / 커뮤니티 게시글 UI 개선

---

.github/workflows/dev-deploy.yml

서버 파일과의 충돌을 방지하기 위해 fetch 방식을 pull로 변경

브랜치 pull 방식 변경

---

frontend/src/components/Community/Article/ArticleEdit/ArticleEdit.jsx
osp/community/views.py

fix: 글 수정이 되지 않는 버그 해결

---

.github/workflows/dev-deploy.yml
.github/workflows/main-deploy-on-release.yml

runner의 라벨을 다르게 하여 동시에 작동하지 않도록 수정

fix: runner 라벨 수정

---

osp/Dockerfile

개발 서버에서 수집이 안되고 있었는데, 도커에서 크롬을 설치하지 않아서 생긴 문제였습니다.
개발 서버 환경에서도 동일하게 크롬을 설치하도록 수정했습니다

chore: 개발환경에서도 크롬을 설치하도록 변경
